---
development:
  cloud_name: <%= Rails.application.secrets[:cloud_name] %>
  api_key: <%= Rails.application.secrets[:api_key] %>
  api_secret: <%= Rails.application.secrets[:api_cloud]%>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= ENV[:cloud_name] %>
  api_key: <%= ENV[:api_key] %>
  api_secret: <%= ENV[:api_cloud]%>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= Rails.application.secrets[:cloud_name] %>
  api_key: <%= Rails.application.secrets[:api_key] %>
  api_secret: <%= Rails.application.secrets[:api_cloud]%>
  enhance_image_tag: true
  static_image_support: false
