# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5983cf37ebe809b5357baa477336c11bb7d28777079e06b41479bf22cd1377d78716b25ddddf1db9cd44056d33aa33249df6f83e330c3c643910af480e9d30bb
  cloud_name: <%= ENV["WWALDO_CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["WWALDO_CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["WWALDO_CLOUDINARY_API_SECRET"] %>

test:
  secret_key_base: d16f8eef071031a28ad26895d4f0331782d5eb7d11c05c900437f719e655b8f4e46fc27cdf98e18ca77021cb472e36b15ded6591cb545d20575650df55cb63dc
  cloud_name: <%= ENV["WWALDO_CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["WWALDO_CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["WWALDO_CLOUDINARY_API_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  cloud_name: <%= ENV["WWALDO_CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["WWALDO_CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["WWALDO_CLOUDINARY_API_SECRET"] %>
